org.gradle.jvmargs=-Xmx4096M
org.gradle.daemon=false

version=6.3.4
group=net.creeperhost.minetogethercommunity
java_version=25

minecraft_version=26.1.2
minecraft_version_range=[26.1.2,26.2)
neo_form_version=26.1.2-1
enabled_platforms=fabric,neoforge

archives_base_name=minetogethercommunity
mod_version=6.3.4
maven_group=net.creeperhost.minetogethercommunity
mod_name=MineTogether Community
mod_author=covers1624, Gigabit101, Cloudhunter, CreeperHost!
mod_id=minetogethercommunity
license=GNU General Public License v3.0
credits=
description=

fabric_loader_version=0.19.2
fabric_version=0.146.1+26.1.2
fabric_api_version=0.146.1+26.1.2

neoforge_version=26.1.2.75
neoforge_loader_version_range=[4,)

polylib_group=net.creeperhost.polylib
polylib_version=26.1.2-2.0.9
polylib_mod_version=2.0.8
jankson_version=1.2.1
mtlib_version=3.8
mtsession_version=1.2.7
mtproxy_version=2.0.26
quack_version=0.4.10.105

#ftb_companion_version=21.1.0-beta.1+mc1.21.1
#ftb_quests_version=2100.1.4
