org.gradle.jvmargs=-Xmx4096M
org.gradle.daemon=false

minecraft_version=1.8.9
forge_version=11.15.1.2318-1.8.9
enabled_platforms=forge
ci_java_version=8
mappings_channel=stable
mappings_version=22

archives_base_name=minetogethercommunity
mod_version=6.4.1-1.8.9
maven_group=net.creeperhost.minetogethercommunity

mtlib_version=3.9
mtsession_version=1.2.7
mtproxy_version=2.0.26
