pluginManagement {
    repositories {
        maven { url "https://maven.fabricmc.net/" }
        maven { url "https://maven.architectury.dev/" }
        maven { url "https://maven.minecraftforge.net/" }
        gradlePluginPortal()
    }
}

include("common")
include("fabric")
include("neoforge")

if (file(".polylib-repo/settings.gradle").exists()) {
    includeBuild(".polylib-repo") {
        dependencySubstitution {
            substitute module("net.creeperhost:polylib-fabric") using project(":fabric")
        }
    }
}

rootProject.name = "MineTogether Community"
