plugins {
    id 'multiloader-common'
    id 'net.neoforged.moddev'
}

neoForge {
    neoFormVersion = neo_form_version
    def at = file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
    }
}

dependencies {
    compileOnly group: 'org.spongepowered', name: 'mixin', version: '0.8.5'
    compileOnly group: 'io.github.llamalad7', name: 'mixinextras-common', version: '0.5.3'
    annotationProcessor group: 'io.github.llamalad7', name: 'mixinextras-common', version: '0.5.3'
    compileOnly 'org.ow2.asm:asm:9.7.1'

    compileOnly("${polylib_group}:polylib-fabric:${polylib_version}") { transitive = false }
    compileOnly "blue.endless:jankson:${jankson_version}"
    compileOnly("net.creeperhost:MineTogetherLib:${mtlib_version}") {
        exclude group: "net.creeperhost", module: "MineTogetherSessions"
    }
    compileOnly("net.creeperhost:MineTogetherSessions:${mtsession_version}") {
        transitive = false
    }
    compileOnly("net.creeperhost:MTConnectProxyCommon:${mtproxy_version}") {
        exclude group: "net.creeperhost", module: "MineTogetherSessions"
        exclude group: "net.creeperhost", module: "MineTogetherLib"
    }
    compileOnly("net.covers1624:Quack:${quack_version}") { transitive = false }

    compileOnly 'org.nanohttpd:nanohttpd:2.3.1'
    compileOnly 'org.apache.httpcomponents:httpclient:4.5.14'
    compileOnly 'com.github.scribejava:scribejava-apis:6.9.0'
    compileOnly 'com.github.scribejava:scribejava-core:6.9.0'

    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.8.2'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.8.2'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher:1.8.2'

    //TODO we should start putting this on maven so we don't need to keep the jar around
//    compileOnly('minetogetherpartners-neoforge:minetogetherpartners-neoforge:1.21-6.3.4')
}

configurations {
    commonJava {
        canBeResolved = false
        canBeConsumed = true
    }
    commonResources {
        canBeResolved = false
        canBeConsumed = true
    }
}

artifacts {
    commonJava sourceSets.main.java.sourceDirectories.singleFile
    commonResources sourceSets.main.resources.sourceDirectories.singleFile
}

def loaderAttribute = Attribute.of('io.github.mcgradleconventions.loader', String)
['apiElements', 'runtimeElements', 'sourcesElements', 'javadocElements'].each { variant ->
    configurations.named("$variant") {
        attributes {
            attribute(loaderAttribute, 'common')
        }
    }
}
sourceSets.configureEach {
    [it.compileClasspathConfigurationName, it.runtimeClasspathConfigurationName].each { variant ->
        configurations.named("$variant") {
            attributes {
                attribute(loaderAttribute, 'common')
            }
        }
    }
}

test {
    useJUnitPlatform()
}
